version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: local_postgres
    environment:
      POSTGRES_USER: finalsign_owner
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: finalsign
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local_dev_network

  minio:
    image: minio/minio:latest
    container_name: local_minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - local_dev_network

volumes:
  postgres_data:
  minio_data:

networks:
  local_dev_network:
    driver: bridge
