services:
  psql_finalsign:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1234
    ports:
      - "5432:5432"
    volumes:
      - psql_volume_finalsign:/var/lib/postgresql/data

volumes:
  psql_volume_finalsign:
