version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: local_postgres
    environment:
      POSTGRES_USER: finalsign_owner
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: finalsign
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local_dev_network

volumes:
  postgres_data:

networks:
  local_dev_network:
    driver: bridge
